/** @type {import('@commitlint/types').UserConfig} */
module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'header-max-length': [2, 'always', 100],
    'body-max-line-length': [1, 'always', 120],
    'scope-enum': [
      2,
      'always',
      [
        'app',
        'api',
        'auth',
        'auth-ui',
        'backend',
        'bookmarks',
        'bookmarks-ui',
        'build',
        'ci',
        'claude',
        'course-detail',
        'courses',
        'courses-ui',
        'db',
        'deps',
        'docker',
        'e2e',
        'editorconfig',
        'episodes',
        'examples',
        'flashcards',
        'flashcards-ui',
        'frontend',
        'husky',
        'lib',
        'libraries',
        'libraries-ui',
        'library',
        'notes',
        'notes-ui',
        'player',
        'progress',
        'readme',
        'release',
        'review-page',
        'scanner',
        'search',
        'search-ui',
        'security',
        'settings',
        'settings/account',
        'settings/connection',
        'settings/libraries',
        'settings/sessions',
        'shares',
        'storybook',
        'stores',
        'subtitles',
        'thumbnails',
        'transcode',
        'ui',
        'vscode',
        'watch-later',
        'watch-later-ui',
      ],
    ],
  },
};
