spring.profiles.include=encryption-stage,voltage-stage

# LOG
server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i" "%{X-Forwarded-For}i" "%{X-Forwarded-Proto}i" "%{X-App-Name}i"
server.tomcat.accesslog.enabled=true

# VAULT

vault.service.baseUrl=https://ws-vault.e2e2.gid.gap.com/
vault.service.username=prepvsclient
vault.service.password={cipher}112476bdc0a47719fb6eb2e8175bb3a6d8a92ea6967b6ab4aba1ff923020ded4
vault.service.retries=3
vault.service.waitInMillis=100
vault.service.connectTimeoutInMillis=5000
vault.service.readTimeoutInMillis=5000
vault.service.checkoutConnectionFromPoolTimeoutInMillis=5000
vault.service.maxConnections=100
vault.service.maxConnectionPerRoute=10
vault.service.previewBaseUrl=https://secure-ws-vaultpreview.e2e2.gid.gap.com/
vault.service.previewUserName=prepvsclient
vault.service.previewPassword={cipher}112476bdc0a47719fb6eb2e8175bb3a6d8a92ea6967b6ab4aba1ff923020ded4
vault.service.previewMaxConnections=10
vault.service.legacyEnabled=true


#SPRINGFOX SWAGGER
springfox.documentation.swagger.version=1.0
springfox.documentation.swagger.title=Vault Service
springfox.documentation.swagger.description=Vault service to manage vault ids.
springfox.documentation.swagger.contactName=Profile Team
springfox.documentation.swagger.contactUrl=http://www.gap.com
springfox.documentation.swagger.contactEmail=HQ-GAPTECH-PROFILE-DG@gap.com
springfox.documentation.swagger.host=stage.api.gap.com
springfox.documentation.swagger.path=commerce/vault
springfox.documentation.swagger.v2.path=/api-docs


management.endpoints.web.exposure.include=refresh,info,health,routes