-------------------------------------------------------------------------------------------------------------------
# The user name and password to access the ingrian box
Ingrian_Username=vpreuser
Ingrian_Password=F11lt3r07$
