bluefin.host=https://secure-cert.shieldconex.com
bluefin.tokenizePath=/api/tokenization/tokenize
bluefin.deTokenizePath=/api/tokenization/detokenize
bluefin.bulkTokenizePath=/api/tokenization/batch/tokenize
bluefin.bulkDeTokenizePath=/api/tokenization/batch/detokenize
bluefin.partnerId=gap_hmac
bluefin.partnerKey=792acf683510feec554dd6719ea9e907
bluefin.reference=test123
bluefin.templateRefCreditCard=bc5d057b503920077bdf0bfa785aae6f
bluefin.templateRefGiftCard=3594ea3b576981294b3c46bb6233c3d6

# RestTemplate configuration
restTemplate.connectTimeOut=0
restTemplate.tokenizeTimeOut=50
restTemplate.detokenizeTimeOut=50
restTemplate.bulkTokenizeTimeOut=80
restTemplate.bulkDetokenizeTimeOut=80

#Connection Pool Configuration
restTemplate.httpClientsMaxConnTotal=80
restTemplate.httpClientsMaxConnPerRoute=20
restTemplate.httpClientsValidateAfterInactivity=2000
restTemplate.httpClientsCheckoutConnTimeout=5000

# Resiliece4j Retry Configuration
resilience4j.retry.instances.bluefin-client-tokenize.max-attempts=3
resilience4j.retry.instances.bluefin-client-tokenize.wait-duration=10ms
resilience4j.retry.instances.bluefin-client-tokenize.exponential-max-wait-duration=25ms
resilience4j.retry.instances.bluefin-client-tokenize.enable-exponential-backoff=true
resilience4j.retry.instances.bluefin-client-tokenize.exponential-backoff-multiplier=2
resilience4j.retry.instances.bluefin-client-tokenize.retry-exceptions=org.springframework.web.client.ResourceAccessException

resilience4j.retry.instances.bluefin-client-detokenize.max-attempts=3
resilience4j.retry.instances.bluefin-client-detokenize.wait-duration=10ms
resilience4j.retry.instances.bluefin-client-detokenize.exponential-max-wait-duration=25ms
resilience4j.retry.instances.bluefin-client-detokenize.enable-exponential-backoff=true
resilience4j.retry.instances.bluefin-client-detokenize.exponential-backoff-multiplier=2
resilience4j.retry.instances.bluefin-client-detokenize.retry-exceptions=org.springframework.web.client.ResourceAccessException