name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  typecheck:
    runs-on: ubuntu-latest
    env:
      ONMO_REGISTRY_PACKAGES: ${{ secrets.ONMO_REGISTRY_PACKAGES }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm run typecheck

  prettier:
    runs-on: ubuntu-latest
    env:
      ONMO_REGISTRY_PACKAGES: ${{ secrets.ONMO_REGISTRY_PACKAGES }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm run lint

  terraform:
    uses: ./.github/workflows/terraform.yaml
    with:
      environment: staging
      validate_only: true
    secrets: inherit

  pr-checks:
    if: always()
    needs: [typecheck, prettier, terraform]
    runs-on: ubuntu-latest
    steps:
      - name: Check all jobs passed
        run: |
          if [[ "${{ needs.typecheck.result }}" != "success" ||
                "${{ needs.prettier.result }}" != "success" ||
                "${{ needs.terraform.result }}" != "success" ]]; then
            echo "One or more checks failed"
            exit 1
          fi
