//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.25 at 08:01:50 AM PDT 
//


package com.voltage.v1.client;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.voltage.v1.client package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.voltage.v1.client
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Fault }
     * 
     */
    public Fault createFault() {
        return new Fault();
    }

    /**
     * Create an instance of {@link ProtectDataResponse }
     * 
     */
    public ProtectDataResponse createProtectDataResponse() {
        return new ProtectDataResponse();
    }

    /**
     * Create an instance of {@link ProtectData }
     * 
     */
    public ProtectData createProtectData() {
        return new ProtectData();
    }

    /**
     * Create an instance of {@link ProtectUnsignedDataResponse }
     * 
     */
    public ProtectUnsignedDataResponse createProtectUnsignedDataResponse() {
        return new ProtectUnsignedDataResponse();
    }

    /**
     * Create an instance of {@link ProtectUnsignedData }
     * 
     */
    public ProtectUnsignedData createProtectUnsignedData() {
        return new ProtectUnsignedData();
    }

    /**
     * Create an instance of {@link AccessDataResponse }
     * 
     */
    public AccessDataResponse createAccessDataResponse() {
        return new AccessDataResponse();
    }

    /**
     * Create an instance of {@link AccessData }
     * 
     */
    public AccessData createAccessData() {
        return new AccessData();
    }

    /**
     * Create an instance of {@link GetAccessListResponse }
     * 
     */
    public GetAccessListResponse createGetAccessListResponse() {
        return new GetAccessListResponse();
    }

    /**
     * Create an instance of {@link GetAccessList }
     * 
     */
    public GetAccessList createGetAccessList() {
        return new GetAccessList();
    }

    /**
     * Create an instance of {@link ProtectCreditCardNumberResponse }
     * 
     */
    public ProtectCreditCardNumberResponse createProtectCreditCardNumberResponse() {
        return new ProtectCreditCardNumberResponse();
    }

    /**
     * Create an instance of {@link ProtectCreditCardNumber }
     * 
     */
    public ProtectCreditCardNumber createProtectCreditCardNumber() {
        return new ProtectCreditCardNumber();
    }

    /**
     * Create an instance of {@link AccessCreditCardNumberResponse }
     * 
     */
    public AccessCreditCardNumberResponse createAccessCreditCardNumberResponse() {
        return new AccessCreditCardNumberResponse();
    }

    /**
     * Create an instance of {@link AccessCreditCardNumber }
     * 
     */
    public AccessCreditCardNumber createAccessCreditCardNumber() {
        return new AccessCreditCardNumber();
    }

    /**
     * Create an instance of {@link ProtectSocialSecurityNumberResponse }
     * 
     */
    public ProtectSocialSecurityNumberResponse createProtectSocialSecurityNumberResponse() {
        return new ProtectSocialSecurityNumberResponse();
    }

    /**
     * Create an instance of {@link ProtectSocialSecurityNumber }
     * 
     */
    public ProtectSocialSecurityNumber createProtectSocialSecurityNumber() {
        return new ProtectSocialSecurityNumber();
    }

    /**
     * Create an instance of {@link AccessSocialSecurityNumberResponse }
     * 
     */
    public AccessSocialSecurityNumberResponse createAccessSocialSecurityNumberResponse() {
        return new AccessSocialSecurityNumberResponse();
    }

    /**
     * Create an instance of {@link AccessSocialSecurityNumber }
     * 
     */
    public AccessSocialSecurityNumber createAccessSocialSecurityNumber() {
        return new AccessSocialSecurityNumber();
    }

    /**
     * Create an instance of {@link ProtectFormattedDataResponse }
     * 
     */
    public ProtectFormattedDataResponse createProtectFormattedDataResponse() {
        return new ProtectFormattedDataResponse();
    }

    /**
     * Create an instance of {@link ProtectFormattedData }
     * 
     */
    public ProtectFormattedData createProtectFormattedData() {
        return new ProtectFormattedData();
    }

    /**
     * Create an instance of {@link AccessFormattedDataResponse }
     * 
     */
    public AccessFormattedDataResponse createAccessFormattedDataResponse() {
        return new AccessFormattedDataResponse();
    }

    /**
     * Create an instance of {@link AccessFormattedData }
     * 
     */
    public AccessFormattedData createAccessFormattedData() {
        return new AccessFormattedData();
    }

    /**
     * Create an instance of {@link ProtectCreditCardNumberListResponse }
     * 
     */
    public ProtectCreditCardNumberListResponse createProtectCreditCardNumberListResponse() {
        return new ProtectCreditCardNumberListResponse();
    }

    /**
     * Create an instance of {@link ProtectCreditCardNumberList }
     * 
     */
    public ProtectCreditCardNumberList createProtectCreditCardNumberList() {
        return new ProtectCreditCardNumberList();
    }

    /**
     * Create an instance of {@link AccessCreditCardNumberListResponse }
     * 
     */
    public AccessCreditCardNumberListResponse createAccessCreditCardNumberListResponse() {
        return new AccessCreditCardNumberListResponse();
    }

    /**
     * Create an instance of {@link AccessCreditCardNumberList }
     * 
     */
    public AccessCreditCardNumberList createAccessCreditCardNumberList() {
        return new AccessCreditCardNumberList();
    }

    /**
     * Create an instance of {@link ProtectSocialSecurityNumberListResponse }
     * 
     */
    public ProtectSocialSecurityNumberListResponse createProtectSocialSecurityNumberListResponse() {
        return new ProtectSocialSecurityNumberListResponse();
    }

    /**
     * Create an instance of {@link ProtectSocialSecurityNumberList }
     * 
     */
    public ProtectSocialSecurityNumberList createProtectSocialSecurityNumberList() {
        return new ProtectSocialSecurityNumberList();
    }

    /**
     * Create an instance of {@link AccessSocialSecurityNumberListResponse }
     * 
     */
    public AccessSocialSecurityNumberListResponse createAccessSocialSecurityNumberListResponse() {
        return new AccessSocialSecurityNumberListResponse();
    }

    /**
     * Create an instance of {@link AccessSocialSecurityNumberList }
     * 
     */
    public AccessSocialSecurityNumberList createAccessSocialSecurityNumberList() {
        return new AccessSocialSecurityNumberList();
    }

    /**
     * Create an instance of {@link ProtectFormattedDataListResponse }
     * 
     */
    public ProtectFormattedDataListResponse createProtectFormattedDataListResponse() {
        return new ProtectFormattedDataListResponse();
    }

    /**
     * Create an instance of {@link ProtectFormattedDataList }
     * 
     */
    public ProtectFormattedDataList createProtectFormattedDataList() {
        return new ProtectFormattedDataList();
    }

    /**
     * Create an instance of {@link AccessFormattedDataListResponse }
     * 
     */
    public AccessFormattedDataListResponse createAccessFormattedDataListResponse() {
        return new AccessFormattedDataListResponse();
    }

    /**
     * Create an instance of {@link AccessFormattedDataList }
     * 
     */
    public AccessFormattedDataList createAccessFormattedDataList() {
        return new AccessFormattedDataList();
    }

    /**
     * Create an instance of {@link ProtectCreditCardNumberV2Response }
     * 
     */
    public ProtectCreditCardNumberV2Response createProtectCreditCardNumberV2Response() {
        return new ProtectCreditCardNumberV2Response();
    }

    /**
     * Create an instance of {@link ProtectCreditCardNumberV2 }
     * 
     */
    public ProtectCreditCardNumberV2 createProtectCreditCardNumberV2() {
        return new ProtectCreditCardNumberV2();
    }

    /**
     * Create an instance of {@link ProtectSocialSecurityNumberV2Response }
     * 
     */
    public ProtectSocialSecurityNumberV2Response createProtectSocialSecurityNumberV2Response() {
        return new ProtectSocialSecurityNumberV2Response();
    }

    /**
     * Create an instance of {@link ProtectSocialSecurityNumberV2 }
     * 
     */
    public ProtectSocialSecurityNumberV2 createProtectSocialSecurityNumberV2() {
        return new ProtectSocialSecurityNumberV2();
    }

    /**
     * Create an instance of {@link ProtectFormattedDataV2Response }
     * 
     */
    public ProtectFormattedDataV2Response createProtectFormattedDataV2Response() {
        return new ProtectFormattedDataV2Response();
    }

    /**
     * Create an instance of {@link ProtectFormattedDataV2 }
     * 
     */
    public ProtectFormattedDataV2 createProtectFormattedDataV2() {
        return new ProtectFormattedDataV2();
    }

    /**
     * Create an instance of {@link ProtectCreditCardNumberListV2Response }
     * 
     */
    public ProtectCreditCardNumberListV2Response createProtectCreditCardNumberListV2Response() {
        return new ProtectCreditCardNumberListV2Response();
    }

    /**
     * Create an instance of {@link ProtectCreditCardNumberListV2 }
     * 
     */
    public ProtectCreditCardNumberListV2 createProtectCreditCardNumberListV2() {
        return new ProtectCreditCardNumberListV2();
    }

    /**
     * Create an instance of {@link ProtectSocialSecurityNumberListV2Response }
     * 
     */
    public ProtectSocialSecurityNumberListV2Response createProtectSocialSecurityNumberListV2Response() {
        return new ProtectSocialSecurityNumberListV2Response();
    }

    /**
     * Create an instance of {@link ProtectSocialSecurityNumberListV2 }
     * 
     */
    public ProtectSocialSecurityNumberListV2 createProtectSocialSecurityNumberListV2() {
        return new ProtectSocialSecurityNumberListV2();
    }

    /**
     * Create an instance of {@link ProtectFormattedDataListV2Response }
     * 
     */
    public ProtectFormattedDataListV2Response createProtectFormattedDataListV2Response() {
        return new ProtectFormattedDataListV2Response();
    }

    /**
     * Create an instance of {@link ProtectFormattedDataListV2 }
     * 
     */
    public ProtectFormattedDataListV2 createProtectFormattedDataListV2() {
        return new ProtectFormattedDataListV2();
    }

    /**
     * Create an instance of {@link AccessFormattedDataV2Response }
     * 
     */
    public AccessFormattedDataV2Response createAccessFormattedDataV2Response() {
        return new AccessFormattedDataV2Response();
    }

    /**
     * Create an instance of {@link AccessFormattedDataV2 }
     * 
     */
    public AccessFormattedDataV2 createAccessFormattedDataV2() {
        return new AccessFormattedDataV2();
    }

    /**
     * Create an instance of {@link AccessFormattedDataListV2Response }
     * 
     */
    public AccessFormattedDataListV2Response createAccessFormattedDataListV2Response() {
        return new AccessFormattedDataListV2Response();
    }

    /**
     * Create an instance of {@link AccessFormattedDataListV2 }
     * 
     */
    public AccessFormattedDataListV2 createAccessFormattedDataListV2() {
        return new AccessFormattedDataListV2();
    }

    /**
     * Create an instance of {@link ProtectGenericDataResponse }
     * 
     */
    public ProtectGenericDataResponse createProtectGenericDataResponse() {
        return new ProtectGenericDataResponse();
    }

    /**
     * Create an instance of {@link ProtectGenericData }
     * 
     */
    public ProtectGenericData createProtectGenericData() {
        return new ProtectGenericData();
    }

    /**
     * Create an instance of {@link AccessGenericDataResponse }
     * 
     */
    public AccessGenericDataResponse createAccessGenericDataResponse() {
        return new AccessGenericDataResponse();
    }

    /**
     * Create an instance of {@link AccessGenericData }
     * 
     */
    public AccessGenericData createAccessGenericData() {
        return new AccessGenericData();
    }

    /**
     * Create an instance of {@link GetGenericDataIdentityResponse }
     * 
     */
    public GetGenericDataIdentityResponse createGetGenericDataIdentityResponse() {
        return new GetGenericDataIdentityResponse();
    }

    /**
     * Create an instance of {@link GetGenericDataIdentity }
     * 
     */
    public GetGenericDataIdentity createGetGenericDataIdentity() {
        return new GetGenericDataIdentity();
    }

    /**
     * Create an instance of {@link ProtectGenericDataListResponse }
     * 
     */
    public ProtectGenericDataListResponse createProtectGenericDataListResponse() {
        return new ProtectGenericDataListResponse();
    }

    /**
     * Create an instance of {@link ProtectGenericDataList }
     * 
     */
    public ProtectGenericDataList createProtectGenericDataList() {
        return new ProtectGenericDataList();
    }

    /**
     * Create an instance of {@link AccessGenericDataListResponse }
     * 
     */
    public AccessGenericDataListResponse createAccessGenericDataListResponse() {
        return new AccessGenericDataListResponse();
    }

    /**
     * Create an instance of {@link AccessGenericDataList }
     * 
     */
    public AccessGenericDataList createAccessGenericDataList() {
        return new AccessGenericDataList();
    }

    /**
     * Create an instance of {@link GetGenericDataIdentityListResponse }
     * 
     */
    public GetGenericDataIdentityListResponse createGetGenericDataIdentityListResponse() {
        return new GetGenericDataIdentityListResponse();
    }

    /**
     * Create an instance of {@link GetGenericDataIdentityList }
     * 
     */
    public GetGenericDataIdentityList createGetGenericDataIdentityList() {
        return new GetGenericDataIdentityList();
    }

    /**
     * Create an instance of {@link ProtectGenericStringDataResponse }
     * 
     */
    public ProtectGenericStringDataResponse createProtectGenericStringDataResponse() {
        return new ProtectGenericStringDataResponse();
    }

    /**
     * Create an instance of {@link ProtectGenericStringData }
     * 
     */
    public ProtectGenericStringData createProtectGenericStringData() {
        return new ProtectGenericStringData();
    }

    /**
     * Create an instance of {@link AccessGenericStringDataResponse }
     * 
     */
    public AccessGenericStringDataResponse createAccessGenericStringDataResponse() {
        return new AccessGenericStringDataResponse();
    }

    /**
     * Create an instance of {@link AccessGenericStringData }
     * 
     */
    public AccessGenericStringData createAccessGenericStringData() {
        return new AccessGenericStringData();
    }

    /**
     * Create an instance of {@link GetGenericStringDataIdentityResponse }
     * 
     */
    public GetGenericStringDataIdentityResponse createGetGenericStringDataIdentityResponse() {
        return new GetGenericStringDataIdentityResponse();
    }

    /**
     * Create an instance of {@link GetGenericStringDataIdentity }
     * 
     */
    public GetGenericStringDataIdentity createGetGenericStringDataIdentity() {
        return new GetGenericStringDataIdentity();
    }

    /**
     * Create an instance of {@link ProtectGenericStringDataListResponse }
     * 
     */
    public ProtectGenericStringDataListResponse createProtectGenericStringDataListResponse() {
        return new ProtectGenericStringDataListResponse();
    }

    /**
     * Create an instance of {@link ProtectGenericStringDataList }
     * 
     */
    public ProtectGenericStringDataList createProtectGenericStringDataList() {
        return new ProtectGenericStringDataList();
    }

    /**
     * Create an instance of {@link AccessGenericStringDataListResponse }
     * 
     */
    public AccessGenericStringDataListResponse createAccessGenericStringDataListResponse() {
        return new AccessGenericStringDataListResponse();
    }

    /**
     * Create an instance of {@link AccessGenericStringDataList }
     * 
     */
    public AccessGenericStringDataList createAccessGenericStringDataList() {
        return new AccessGenericStringDataList();
    }

    /**
     * Create an instance of {@link GetGenericStringDataIdentityListResponse }
     * 
     */
    public GetGenericStringDataIdentityListResponse createGetGenericStringDataIdentityListResponse() {
        return new GetGenericStringDataIdentityListResponse();
    }

    /**
     * Create an instance of {@link GetGenericStringDataIdentityList }
     * 
     */
    public GetGenericStringDataIdentityList createGetGenericStringDataIdentityList() {
        return new GetGenericStringDataIdentityList();
    }

    /**
     * Create an instance of {@link ProtectFormattedDataWithAllKeyNumbers }
     * 
     */
    public ProtectFormattedDataWithAllKeyNumbers createProtectFormattedDataWithAllKeyNumbers() {
        return new ProtectFormattedDataWithAllKeyNumbers();
    }

    /**
     * Create an instance of {@link ProtectFormattedDataWithAllKeyNumbersResponse }
     * 
     */
    public ProtectFormattedDataWithAllKeyNumbersResponse createProtectFormattedDataWithAllKeyNumbersResponse() {
        return new ProtectFormattedDataWithAllKeyNumbersResponse();
    }

    /**
     * Create an instance of {@link ProtectFormattedDataMultiplexedResponse }
     * 
     */
    public ProtectFormattedDataMultiplexedResponse createProtectFormattedDataMultiplexedResponse() {
        return new ProtectFormattedDataMultiplexedResponse();
    }

    /**
     * Create an instance of {@link ProtectFormattedDataMultiplexed }
     * 
     */
    public ProtectFormattedDataMultiplexed createProtectFormattedDataMultiplexed() {
        return new ProtectFormattedDataMultiplexed();
    }

    /**
     * Create an instance of {@link AccessFormattedDataMultiplexedResponse }
     * 
     */
    public AccessFormattedDataMultiplexedResponse createAccessFormattedDataMultiplexedResponse() {
        return new AccessFormattedDataMultiplexedResponse();
    }

    /**
     * Create an instance of {@link AccessFormattedDataMultiplexed }
     * 
     */
    public AccessFormattedDataMultiplexed createAccessFormattedDataMultiplexed() {
        return new AccessFormattedDataMultiplexed();
    }

    /**
     * Create an instance of {@link AccessFormattedDataMultiplexedV2Response }
     * 
     */
    public AccessFormattedDataMultiplexedV2Response createAccessFormattedDataMultiplexedV2Response() {
        return new AccessFormattedDataMultiplexedV2Response();
    }

    /**
     * Create an instance of {@link AccessFormattedDataMultiplexedV2 }
     * 
     */
    public AccessFormattedDataMultiplexedV2 createAccessFormattedDataMultiplexedV2() {
        return new AccessFormattedDataMultiplexedV2();
    }

    /**
     * Create an instance of {@link ProtectFormattedDataListMultiplexedResponse }
     * 
     */
    public ProtectFormattedDataListMultiplexedResponse createProtectFormattedDataListMultiplexedResponse() {
        return new ProtectFormattedDataListMultiplexedResponse();
    }

    /**
     * Create an instance of {@link ProtectFormattedDataListMultiplexed }
     * 
     */
    public ProtectFormattedDataListMultiplexed createProtectFormattedDataListMultiplexed() {
        return new ProtectFormattedDataListMultiplexed();
    }

    /**
     * Create an instance of {@link AccessFormattedDataListMultiplexedResponse }
     * 
     */
    public AccessFormattedDataListMultiplexedResponse createAccessFormattedDataListMultiplexedResponse() {
        return new AccessFormattedDataListMultiplexedResponse();
    }

    /**
     * Create an instance of {@link AccessFormattedDataListMultiplexed }
     * 
     */
    public AccessFormattedDataListMultiplexed createAccessFormattedDataListMultiplexed() {
        return new AccessFormattedDataListMultiplexed();
    }

    /**
     * Create an instance of {@link AccessFormattedDataListMultiplexedV2Response }
     * 
     */
    public AccessFormattedDataListMultiplexedV2Response createAccessFormattedDataListMultiplexedV2Response() {
        return new AccessFormattedDataListMultiplexedV2Response();
    }

    /**
     * Create an instance of {@link AccessFormattedDataListMultiplexedV2 }
     * 
     */
    public AccessFormattedDataListMultiplexedV2 createAccessFormattedDataListMultiplexedV2() {
        return new AccessFormattedDataListMultiplexedV2();
    }

    /**
     * Create an instance of {@link EchoDataResponse }
     * 
     */
    public EchoDataResponse createEchoDataResponse() {
        return new EchoDataResponse();
    }

    /**
     * Create an instance of {@link EchoData }
     * 
     */
    public EchoData createEchoData() {
        return new EchoData();
    }

    /**
     * Create an instance of {@link EchoDataListResponse }
     * 
     */
    public EchoDataListResponse createEchoDataListResponse() {
        return new EchoDataListResponse();
    }

    /**
     * Create an instance of {@link EchoDataList }
     * 
     */
    public EchoDataList createEchoDataList() {
        return new EchoDataList();
    }

    /**
     * Create an instance of {@link ProtectFormattedDataRangeList }
     * 
     */
    public ProtectFormattedDataRangeList createProtectFormattedDataRangeList() {
        return new ProtectFormattedDataRangeList();
    }

    /**
     * Create an instance of {@link DataRange }
     * 
     */
    public DataRange createDataRange() {
        return new DataRange();
    }

    /**
     * Create an instance of {@link ProtectFormattedDataRangeListResponse }
     * 
     */
    public ProtectFormattedDataRangeListResponse createProtectFormattedDataRangeListResponse() {
        return new ProtectFormattedDataRangeListResponse();
    }

    /**
     * Create an instance of {@link AccessFormattedDataRangeList }
     * 
     */
    public AccessFormattedDataRangeList createAccessFormattedDataRangeList() {
        return new AccessFormattedDataRangeList();
    }

    /**
     * Create an instance of {@link AccessFormattedDataRangeListResponse }
     * 
     */
    public AccessFormattedDataRangeListResponse createAccessFormattedDataRangeListResponse() {
        return new AccessFormattedDataRangeListResponse();
    }

}
