bluefin.host=https://secure.shieldconex.com
bluefin.tokenizePath=/api/tokenization/tokenize
bluefin.deTokenizePath=/api/tokenization/detokenize
bluefin.bulkTokenizePath=/api/tokenization/batch/tokenize
bluefin.bulkDeTokenizePath=/api/tokenization/batch/detokenize
bluefin.partnerId=GAP
bluefin.partnerKey=0527e792fab464c94e99998a46dcc70a
bluefin.reference=Gap_Vault_Prod
bluefin.templateRef=e2ffc43b7599b08ecd1d2b4c8185c627

# RestTemplate configuration
restTemplate.connectTimeOut=2000
restTemplate.tokenizeTimeOut=50
restTemplate.detokenizeTimeOut=50
restTemplate.bulkTokenizeTimeOut=80
restTemplate.bulkDetokenizeTimeOut=80

#Connection Pool Configuration
restTemplate.httpClientsMaxConnTotal=80
restTemplate.httpClientsMaxConnPerRoute=20
restTemplate.httpClientsValidateAfterInactivity=2000
restTemplate.httpClientsCheckoutConnTimeout=5000

# Resiliece4j Retry Configuration
resilience4j.retry.instances.bluefin-client-tokenize.max-attempts=3
resilience4j.retry.instances.bluefin-client-tokenize.wait-duration=10ms
resilience4j.retry.instances.bluefin-client-tokenize.exponential-max-wait-duration=25ms
resilience4j.retry.instances.bluefin-client-tokenize.enable-exponential-backoff=true
resilience4j.retry.instances.bluefin-client-tokenize.exponential-backoff-multiplier=2
resilience4j.retry.instances.bluefin-client-tokenize.retry-exceptions=org.springframework.web.client.ResourceAccessException

resilience4j.retry.instances.bluefin-client-detokenize.max-attempts=3
resilience4j.retry.instances.bluefin-client-detokenize.wait-duration=10ms
resilience4j.retry.instances.bluefin-client-detokenize.exponential-max-wait-duration=25ms
resilience4j.retry.instances.bluefin-client-detokenize.enable-exponential-backoff=true
resilience4j.retry.instances.bluefin-client-detokenize.exponential-backoff-multiplier=2
resilience4j.retry.instances.bluefin-client-detokenize.retry-exceptions=org.springframework.web.client.ResourceAccessException