gatling {
  core {
    directory {
      bodies = build/resources/performanceTest/bodies           # Folder where bodies are located
      binaries = build/classes/performanceTest                            # If set, name of the folder where compiles classes are located: Defaults to GATLING_HOME/target.
      results = build/reports/performance                       # Name of the folder where all reports folder are located
    }
  }
}
ws.ssl {
  trustManager = {
     stores = [
      { path: META-INF/security/truststore }     # Added trust store
     ]
  }
}