package types

// WorkflowID identifies a workflow definition family. It is supplied by the
// caller and must be unique within a namespace.
type WorkflowID string

// RunID identifies a single execution of a workflow. It is generated by the
// server when a workflow is started.
type RunID string

// ActivityID identifies a single activity invocation within a workflow run.
// It is assigned by the engine and is monotonically increasing within a run.
type ActivityID uint64

// TaskQueue is a logical bucket workers poll from.
type TaskQueue string

// Namespace partitions workflows. Defaults to "default".
type Namespace string

const DefaultNamespace Namespace = "default"

func (w WorkflowID) String() string { return string(w) }
func (r RunID) String() string      { return string(r) }
func (t TaskQueue) String() string  { return string(t) }
func (n Namespace) String() string  { return string(n) }
