spring.config.import=application-voltage-prod.properties,application-bluefin-prod.properties

# LOG
server.tomcat.accesslog.pattern='%{X-Forwarded-For}i %h %l %u %t "%r" %s %b %{Host}i %D %{True-Client-IP}i %{X-Gid-Client-Session}i "%{X-App-Name}i" %I'
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.directory=/dev
server.tomcat.accesslog.prefix=stdout
server.tomcat.accesslog.buffered=false
server.tomcat.accesslog.suffix=
server.tomcat.accesslog.file-date-format=

server.max-http-header-size=16000

# VAULT
vault.service.baseUrl=https://ws-vault-preview.prod.gaptech.com/
vault.service.username=ecomwsclient
vault.service.password={cipher}20d4f058231035acb5e7a74d633e7b3b893c525f04be7d38d717d25062538c1a
vault.service.retries=3
vault.service.waitInMillis=100
vault.service.connectTimeoutInMillis=5000
vault.service.readTimeoutInMillis=5000
vault.service.checkoutConnectionFromPoolTimeoutInMillis=5000
vault.service.maxConnections=100
vault.service.maxConnectionPerRoute=10
vault.service.previewBaseUrl=https://ws-vault-preview.prod.gaptech.com/
vault.service.previewUserName=ecomwsclient
vault.service.previewPassword={cipher}20d4f058231035acb5e7a74d633e7b3b893c525f04be7d38d717d25062538c1a
vault.service.previewMaxConnections=10

#polling time is in milliseconds
vault.service.pollingTime = 60000

#Azure SQL DB properties
spring.datasource.url=jdbc:sqlserver://g-sdb-2c-profile-customer-vlt-prv-01.database.windows.net:1433;database=VaultSqlServer;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=VaultUser
spring.datasource.password={cipher}bc14c98aef6ec21754652b41c7c0e636e6414ed9a98c9e6d4303589b52a87509cb167a54188192297a11ab539adf44cc
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.PoolMaxSize=30
spring.datasource.PoolMinSize=1
spring.datasource.test-while-idle=true
spring.datasource.test-on-borrow=true
spring.datasource.max-active=30

#SPRINGFOX SWAGGER
springfox.documentation.swagger.version=1.0
springfox.documentation.swagger.title=Vault Service
springfox.documentation.swagger.description=Vault service to manage vault ids.
springfox.documentation.swagger.contactName=Profile Team
springfox.documentation.swagger.contactUrl=http://www.gap.com
springfox.documentation.swagger.contactEmail=HQ-GAPTECH-PROFILE-DG@gap.com
springfox.documentation.swagger.host=api.gap.com
springfox.documentation.swagger.path=commerce/vault
springfox.documentation.swagger.v2.path=/api-docs

#Used for enabling Actuator Endpoints.
management.endpoints.web.exposure.include=health,loggers,info
management.health.defaults.enabled=false
spring.cloud.discovery.client.composite-indicator.enabled=false
management.endpoint.health.show-details=always

ingrian.configfile=/IngrianNAE-prod.properties
vaultserver.configfile=/vaultserver-prodpreview.properties

#Resiliance retry config properties for Azure
resilience4j.retry.instances.db-retry-azure.max-attempts=3
resilience4j.retry.instances.db-retry-azure.wait-duration=10ms
resilience4j.retry.instances.db-retry-azure.enable-exponential-backoff=true
resilience4j.retry.instances.db-retry-azure.exponential-backoff-multiplier=2
resilience4j.retry.instances.db-retry-azure.retry-exceptions=java.util.concurrent.TimeoutException