//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.25 at 08:01:50 AM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://voltage.com/vibesimple")
package com.voltage.v1.client;
