environment: "prod"
logging_level: "INFO"

urls:
  ONMO_AUTH_URL: "auth.onmo.app"
  ONMO_API_URL: "api.onmo.app"
  FRONTEND_URL: "https://onmo.app"
  CARD_SERVICE_BASE_URL: "https://internal-api.onmo.app/service/cards/v1"

gateways:
  APR_GATEWAY_ID: "8i2cyyl8g5"
  CUSTOMER_CARE_GATEWAY_ID: "8vm3007bol"
  AUTHENTICATION_GATEWAY_ID: "96ijknxkn6"
  CARD_SERVICE_OIDC_GATEWAY_ID: "tdxxhicneh"
  ACCOUNT_SERVICE_OIDC_GATEWAY_ID: "jjdh6sb9yj"
  CUSTOMER_SERVICE_OIDC_GATEWAY_ID: "d9a2wgjga1"
  REPAYMENT_SERVICE_GATEWAY_ID: "4mlsnfz14k"
  ALERT_SERVICE_OIDC_GATEWAY_ID: "1lbld4myxe"
  TRANSACTION_SERVICE_OIDC_GATEWAY_ID: "bpi7nqapc3"
  DEVICE_CHANNEL_GATEWAY_ID: "2f657img6j"
  BIOMETRICS_SERVICE_GATEWAY_ID: "284kw57ac4"

gateway_config:
  THROTTLING_BURST_LIMIT: 6000
  THROTTLING_RATE_LIMIT: 2000
  CUSTOM_DOMAIN_NAMES:
    - "auth.onmo.app"

alerting:
  SLACK_CHANNEL: "alerts-prod"
  ALERT_EMAIL_LIST:
    - "joe.kadi@onmo.app"
    - "felix.bait@onmo.app"
    - "michael.edwards@onmo.app"
    - "luke.holroyd@onmo.app"

sfmc:
  NOTIFICATIONS_SFMC_CLIENT_ID: "0xw8tgqrljd6maqvkeilyqj9"
  NOTIFICATIONS_SFMC_ACCOUNT_ID: "536006153"
  NOTIFICATIONS_SFMC_EVENT_KEY_OTP: "APIEvent-059d703d-f2f3-0bca-57aa-a5c986cc3e80"

# Non-standard SSM paths (don't follow /onmo/auth/{env}/ pattern)
params:
  RATE_LIMITING_PARAM: "/onmo/rate_limiting/prod/domains"
  DOWNLOAD_APP_REDIRECT_URL_CONFIG: "/onmo/onboarding/prod/download_app_redirect_url_config"

misc:
  QA_BYPASS_CUSTOMER_IDS: ""

test_scopes: {}
