export const ERROR_CODES = {
  CONFIG_SERVICE_ERROR: "CONFIG_SERVICE_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",
  BANKING_SERVICE_ERROR: "BANKING_SERVICE_ERROR",
  ACCOUNT_INVALID_STATE: "ACCOUNT_INVALID_STATE",
  RATE_LIMIT_SERVICE_ERROR: "RATE_LIMIT_SERVICE_ERROR",
  BIOMETRICS_VERIFICATION_ERROR: "BIOMETRICS_VERIFICATION_ERROR",
  PASSCODE_MIGRATION_ERROR: "PASSCODE_MIGRATION_ERROR",
} as const;
