


# VOLTAGE

voltage.service.identity=pci@gapinc.com
voltage.service.tokenizeAuthInfo=jMC6HWLRHoboP0d9eZ8N
voltage.service.deTokenizeAuthInfo=jMC6HWLRHoboP0d9eZ8N
voltage.service.format=firstsixlastfour
voltage.service.callbackUrl=http://voltage.com/vibesimple
voltage.service.serviceUrl=https://voltage-pp-0000.gapinc.com/vibesimple/services
voltage.service.connectionTimeout=30000
voltage.service.readTimeout=30000
voltage.service.maxTotalConnections=50
